### ISSUE TITLE
Add a Contribution Guide

### ISSUE THREAD

**Issue by hellozee** [ILUGD/splatter#7]

**Comment by miphilomath** [comment]
What do we need to add in the contribution Guide? Following are my thoughts, do give your thoughts: 
* Indexing styles and naming conventions. If golang have any standard method as in PEP-8 python, we can impose that.
* How to open an issue? Add proper title to your issue, add the system details and the method to replicate it.
* How to pick a task? Always notify others before picking any task by commenting on the issue.
* How to create pull request? Always fork the project and make the changes on a separate branch before making a pull request.

Finally, If you feel you need help anywhere, don't hesitate to ask questions on our telegram channel or IRC channel.

**Comment by hellozee** [comment]
### Styles and naming conventions
 - run the code through `goimports` before committing
 - structs/functions should be documented in the following manner
 ```
 //Function/Struct Name <2 spaces> What it does
Function/Struct definition
```
 - Try to keep the lines short typically to 75 - 80 chars at most
 - Naming should only be done in camelCase

### Opening an Issue
 - Issue should start with the package associated with it., followed by a colon and short description*
**Example** : `parser: Variable a is not being parsed`
 - Append [Issue] if it is a problem, [Request] if it is a feature request to the description
 - Don't use punctuation marks at the end of the title

### Submitting Patches
 - Comment on an issue before starting working on it
 - If it is a feature make a issue on it
 - Start working after you are assigned to the issue
 - Commit Message should begin with the package you have worked on followed by a colon and short description, just like Issue titles *
 - Always append the description with **Fix:** #issue_number
 - Fork and Commit your changes in a separate branch

If you are still not sure about the guidelines, you can ask us on our IRC/matrix channel, Telegram group or Mailing Lists.

*Work on refactoring the code is going on, soon the code will be separated into different packages
#### Note : It is, by no mean the final guidelines, it is just a rough sketch

**Comment by miphilomath** [comment]
Let's make it happen :)

**Comment by sourabhpruthi10** [comment]
I will work on this. Can you please give me some resources so that i can get the template of how the things are to be written

**Comment by hellozee** [comment]
@sourabh1031 sure,go ahead
